### ISSUE TITLE
 Layer Title and Dot Indicator Not Updating with NiceView Gem

### ISSUE THREAD

**Issue by Notaduck** [M165437/nice-view-gem#1]
Hi there! I've been experimenting with the NiceView gem, and it’s working great! However, I’ve noticed that the layer title isn't displayed, and the dot indicators at the bottom don't update when switching layers. Are there any specific configurations or steps I need to follow to get this functionality working?

Here's a link to my ZMK configuration: [zmk-chocofi-config](https://github.com/Notaduck/zmk-chocofi-config).

Thank you for your help!

**Comment by M165437** [comment]
Hey! Do layer title and profile indicator work with the default nice!view shield?

```
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_custom 
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_custom
```
