### ISSUE TITLE
Tips for trouble shooting?

### ISSUE THREAD

**Issue by pmffromspace** [M165437/nice-view-gem#3]
Hey I really like you design and tried the better part of today (as beginner of zmk) to get it working on my corne 36 from keebmaker.
I have the problem, that when I follow the guide, the displays wont show anything.

I noticed, that I normally use config:
```
---
include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right

```
 But after using your guide with following build options the displays wont work.
```
---
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_gem
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_gem
```
This is my repo-branch () https://github.com/pmffromspace/zmk-corne-36/tree/nice-view-gem

Could you maybe point me in the right direction how to debug this?
Kind regards
pmf
